### ISSUE TITLE
'Press ENTER...' prompt on exit is intrusive

### ISSUE THREAD

**Issue by PhilRunninger** [romgrk/winteract.vim#1]
Nice job on this plugin! I like the fact that it is so compact. I'm still retraining my fingers, but I think I'll end up liking it a lot. It pairs well with [https://github.com/ap/vim-buftabline](https://github.com/ap/vim-buftabline). I was wondering if you'd consider making a minor change to the code, though.

Whenever I leave interactive window mode, I'm left with the prompt `Press ENTER or type command to continue`. That prompt can disrupt my workflow, depending on what I do next. Considering just the `hjkl` keys, `k` doesn't dismiss the prompt, while the other three do. So if I want to go up a line, I need an extra keystroke.

Removing [lines 132 & 133](https://github.com/romgrk/winteract.vim/blob/master/plugin/window-mode.vim#L132-L133) will solve this issue. The only downside is that we will have lost the notification that the plugin has finished.

**Comment by romgrk** [comment]
Very right! I always use `set cmdheight=2`, so I never noticed that prompt, very bad user experience indeed, I removed the newline after the essential `:)`, so it should now exit cleany. Let me know if it still shows up.

Commit: https://github.com/romgrk/winteract.vim/commit/85031ac5f29d485cf96319a556f0eb9a3e47b908#diff-4166d35b2e3c9a3dc558adfae129c273R133

**Comment by PhilRunninger** [comment]
That does it. Thanks for the quick response.
