### ISSUE TITLE
Allow users to override the mappings

### ISSUE THREAD

**Issue by PhilRunninger** [romgrk/winteract.vim#3]
I finally figured out the problems I had with #2. But I still wasn't able to override the plugins mappings with my own. Unless there's a better way that I'm missing, I was able to make it work by wrapping these lines: https://github.com/romgrk/winteract.vim/blob/master/plugin/window-mode.vim#L23-L86 with this `if` statement.

```
if !exists('g:winmap')
    " lines 23-86
endif
```

Thanks.

**Comment by romgrk** [comment]
Committed that change as proposed, but let's leave this issue open; it would be better to merge the `winmap` of the user with the default one I think.
Commit: 5570639d5867d795d577314fca4caf68efdab250 (it got mangled with some changes I had made w/o committing)

**Comment by PhilRunninger** [comment]
Merging makes sense, as long as user settings replace like-named default mappings. I noticed that, for example, an entry like `"j" : ""` will effectively `<Nop>` the `j` key, a technique one could use to disable any of the default keys.

**Comment by PhilRunninger** [comment]
I'm going to close this issue, because... while I like this plugin, I had decided that I'd be better off learning and using the native window navigation commands. Best wishes to you as you refined this plugin.
